# Site settings
name: Jihwan's Blog
title: Jihwan's Blog
email: jhkim105@gmail.com
author: Jihwan Kim
url: 
resume_site: 
github: https://github.com/jhkim105/
baseurl: ""
description: About Software Development And Maintenance
meta_description: 
motto: Just Do It!
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jhkim105

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

